### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by ghost** [JongeunKeum/42born2code-push_swap#3]
I think that max int have also a problem 
[1]    90381 segmentation fault  ./push_swap 5 9 8 4 2 2147483647

**Comment by ghost** [comment]
problem solved, replace all your "int" by "long" .somewhere you do "int max value + 1" so it's why it segfault. I don't know where. you just have to keep "int main(int argc,..)" but for the rest, just replace your int by long. it's ok because you defined the maximum value in structures.h so you can't go upper.

**Comment by jkeum-dev** [comment]
When I tried, seg-fault did not appear but 'ra' was outputted to infinity.
After reading your feedback and looking at the code again, the pivot seems to be the problem.
When calculating the _pivot_ value, it seems that the wrong value was set as the _pivot_ because it exceeded the maximum range of `int` values in the process of adding the _min_ and _max_ values.
It worked well when I changed the variables related to finding the pivot value from `int` to `long`.
